### ISSUE TITLE
Modpack distribution

### ISSUE THREAD

**Issue by skittishtrigger** [ResqDiver1317/AC-Sauce-1_10_2_modpack#1]
Once basic modpack mod list is done(finalized) how will modpack be distributed?  Alternative to db or a different method?

**Comment by ResqDiver1317** [comment]
Right now, my thoughts are to shutdown the current Sauce pack tonight and build it on the actual server space it will run on. Will help in the long run as we can configure everything around the actual environment it will be on. The client side will be uploaded to Technic via a private pack and all parties that need access to it will be be privately sent the the Technic API/Link to download it via Enjin and/or Discord PMs.

**Comment by skittishtrigger** [comment]
Sounds good. are you going to distro it via zip as a single or use solder for individual updates and versioning?

**Comment by ResqDiver1317** [comment]
My current method is via Zip uploaded to my webspace (which will be even easier now with the DO server for AC Stuff). I don't have a solder setup although, now that I'm thinking about it, having a dedicated AC Solder setup on my DO would be nice. When I get off work today, I'll load that.

**Comment by ResqDiver1317** [comment]
Old Sauce is shut down and being downloaded/deleted to make room for the new server files. should be ready to start loading stuff this evening.
