### ISSUE TITLE
Wither Skellys/Skellys not spawning in Nether

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/AC-Sauce-1_10_2_modpack#13]
Getting ZERO Wither Skeletons or Skeletons spawning in the Nether.

**Comment by ResqDiver1317** [comment]
We need to setup a couple random powered spawners (the JEI has them already loaded with wither skellies) in fortresses. But they need to be triggered by some type of player detector so they only will kick on when someone is near by. Have the trigger set using redstone so it doesn't run constant when someone is there, just triggers on/off which can be done via a timer activating it and the actual signal being interrupted from the player detector with a comparator or some similar setup.

**Comment by Teyrz** [comment]
Not sure if i'm dredging up old news, but you might consider putting them up for sale in the shop with a filled soul vial or something of the sort

**Comment by ResqDiver1317** [comment]
This issue has resolved itself (as expected)
