### ISSUE TITLE
Issue crafting with nuggets

### ISSUE THREAD

**Issue by eternalled** [ResqDiver1317/AC-Sauce-1_10_2_modpack#16]
Example: Servo

Materials: Tin Nuggets, Glass, Iron and Redstone

This may be related to the nugget issue where you can't smelt nuggets to bars.

**Comment by ResqDiver1317** [comment]
Conflict between Agricraft and OreDict/UniDict. Temporary solution is to have the trade chests on the smelter at spawn that you can exchange the Agri Tin/Iron nuggets for Immersive ones.

**Comment by ResqDiver1317** [comment]
Workaround done. used mtrm to remove crafting agri nuggets from ingots and it appears to be working good now. Anyone with existing agri nuggets can swap them with the trade system on the back of the smelter at spawn.
