### ISSUE TITLE
Mega Torch

### ISSUE THREAD

**Issue by eternalled** [ResqDiver1317/AC-Sauce-1_10_2_modpack#17]
Mega Torch does not always work, if at all.

**Comment by ResqDiver1317** [comment]
Yea..... It works sometimes. I think it has a conflict with another mod, just not sure which one yet. I'm leaning towards the BloodMoon, but not sure. I have an issue in with torchmaster about it.

**Comment by ResqDiver1317** [comment]
Mod updated. Closing this. If further issues exist, will open new issue.
