### ISSUE TITLE
Fire (ugh), is getting weird message?

### ISSUE THREAD

**Issue by eternalled** [ResqDiver1317/AC-Sauce-1_10_2_modpack#19]
Wasn't sure if we should put a ticket in for this, however might be a legitimate issue.

He continues to get a message 

[TE] Cannot pay your salary! Contact your administrator!

He is posting a forum post and screen shot

**Comment by ResqDiver1317** [comment]
This is from me working on the payroll system. some people may see it until I get it all worked out.
