### ISSUE TITLE
Welcome Thread. Post here when joining the GIt :)

### ISSUE THREAD

**Issue by Teyrz** [ResqDiver1317/AC-Sauce-1_10_2_modpack#2]
Heya folks, Resq asked me to create a new issue to test ;)

**Comment by Jadedheaven** [comment]
i smell smexiness

**Comment by Badeljamso** [comment]
allo :>

**Comment by Rozarii** [comment]
hello everyone, thank you for inviting me to take part in this new build. I am ready to work just need to be white-listed. :D

**Comment by ResqDiver1317** [comment]
Got you added Roz

**Comment by Rozarii** [comment]
yay, thank you 💃

**Comment by SilviaMarsh** [comment]
Hihi!
