### ISSUE TITLE
Energy Core Stabilizer & Energy Infuser Broken

### ISSUE THREAD

**Issue by eternalled** [ResqDiver1317/AC-Sauce-1_10_2_modpack#21]
Inability to craft both of these items

**Comment by ResqDiver1317** [comment]
Is it the same issue as before with the other items where it shows it completed on the table but just can't pull it out?

**Comment by eternalled** [comment]
Correct

**Comment by ResqDiver1317** [comment]
Ok, when I get back I will grab the ingredients and redo their recipes like I did the others. If you are available to hop on discord then, I'll go over how to do that with you as well

**Comment by eternalled** [comment]
Sounds good, it seems its all draconic recipes, the basic infusion crafting injector doesnt work either.

**Comment by eternalled** [comment]
Energy  Core also not working.

**Comment by ResqDiver1317** [comment]
#23
