### ISSUE TITLE
GPTowns may not be what we need for plots.

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/AC-Sauce-1_10_2_modpack#4]
Spent a while tonight on discord with the guys from GP. It sounds like the GPTowns may not handle the plot buying/selling the way I had hoped so that may be an issue. I gave some input and it looks like part of it they may use, but setting the plots up where players can buy them automatically may end up being a VERY manual process. If so, we may end up having to go a very different route with the plots. I'm keeping an eye on it, but I am not very hopeful on it being specifically what we are looking for.

**Comment by Teyrz** [comment]
Hmm.

Resq just thinking here, is there a mod that can link a purchased item to the economy system? IE: buying a "plot deed" and being charged weekly for it from the player's /balance

**Comment by ResqDiver1317** [comment]
Spent quite a bit of time the last couple nights chatting with the team from GP and the updates they are working on are looking good so I don't think this will actually end up being an issue.
