### ISSUE TITLE
Power Grid Plan B ideas

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/AC-Sauce-1_10_2_modpack#9]
Gonna have to come up with a new plan for the power grid. Original plan was to use HV Wire from Immersive but after testing on a 4 square block area, it was already causing big FPS issues.

**Comment by Teyrz** [comment]
Do we have thermal expansion or Draconic Evolution in the pack?  if we have TE, could use the cryo-stabilized redstone fluxduct under the roads; if we have drac evolution, could use wireless relays in the same way, built underground to get rid of the pesky laser lines out of sight.  You could then branch off from underground with Immersive cables, once per plot; that should limit the FPS issues

**Comment by ResqDiver1317** [comment]
was kicking the idea of cryoducts and was actually about to start ripping up the road for it, then had a though. We are using using creative power anyways, so we could do a creative capacitor for each block, and a place a Basic Capacitor from EIO for each lot and adjust it for a max rf/t flow. that would eliminate the issue of having to keep the whole cryopath chunkloaded as it won't transfer power through unloaded chunks. single setup per block woul dhave it loaded by players when they are on their lot

**Comment by Teyrz** [comment]
the basic capacitor is a hell of an ugly block though.  That was why you were going for IE in the first place.  Can we get away with using some IE lines per plot ? Great idea on the creative cell, just have to put it in under the road so the players can't get access to it.

**Comment by ResqDiver1317** [comment]
My thought was to have the creative cap and the "plot" capacitors all underground and not accessible. Can run IE Wires from the EIO Cap. That way the EIO cap will protect the IE wires from being overloaded

**Comment by Teyrz** [comment]
Yeah good call, just trying to make sure that the output from the capacitor is in keeping with your idea of using the IE hv wire as decoration to make things look sharp.  Sounds like the best plan going
